services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: GENERIC_TIMEZONE
        value: Asia/Almaty
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_LOG_LEVEL
        value: info
      - key: N8N_DIAGNOSTICS_ENABLED
        value: false
      - key: N8N_PAYLOAD_SIZE_MAX
        value: 16
      - key: WEBHOOK_URL
        fromService:
          name: n8n
          type: web
          property: url
    buildCommand: echo "Docker image will be used"
    startCommand: n8n start
    dockerfilePath: ./Dockerfile
    autoDeploy: true
